/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-22 09:05:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/resources/static/jsp/nav.jsp", Long.valueOf(1713776651750L));
    _jspx_dependants.put("/resources/static/jsp/footer.jsp", Long.valueOf(1713776651749L));
    _jspx_dependants.put("/resources/static/jsp/topHeader.jsp", Long.valueOf(1713776651751L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1713776664609L));
    _jspx_dependants.put("jar:file:/C:/JSP/eclipse/worksapce/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/07_MVC_BOOK1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/resources/static/jsp/link.jsp", Long.valueOf(1713776651750L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("\n");
      out.write("	<!-- link  -->\n");
      out.write("	");
      out.write("\n");
      out.write("   \n");
      out.write("<!-- reset.css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/reset-css@5.0.2/reset.min.css\">\n");
      out.write("    \n");
      out.write("<!-- BS Code -->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<!-- axios cdn  -->\n");
      out.write("<script defer src=\"https://cdnjs.cloudflare.com/ajax/libs/axios/1.4.0/axios.min.js\" integrity=\"sha512-uMtXmF28A2Ab/JJO2t/vYhlaa/3ahUOgj1Zf27M5rOo8/+fcTUVH0/E0ll68njmjrLqOBjXM3V9NiPFL5ywWPQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\n");
      out.write("\n");
      out.write("<!-- google icon cdn -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200\" />\n");
      out.write("<style>\n");
      out.write(".material-symbols-outlined {\n");
      out.write("  font-variation-settings:\n");
      out.write("  'FILL' 0,\n");
      out.write("  'wght' 400,\n");
      out.write("  'GRAD' 0,\n");
      out.write("  'opsz' 24\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<!-- swiper.cdn -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css\" />\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	\n");
      out.write("	<!-- common.css -->\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/static/css/common.css\" />\n");
      out.write("	\n");
      out.write("	<!-- common.js -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/static/js/common.js\" defer></script>\n");
      out.write("	\n");
      out.write("	<!-- index.js -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/static/js/index.js\" defer></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	\n");
      out.write("	<div class=\"wrapper\">\n");
      out.write("		<header>\n");
      out.write("			\n");
      out.write("			<!-- top-header -->\n");
      out.write("			");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"top-header layout-150\">\n");
      out.write("				<div class=\"left\"></div>\n");
      out.write("				<div class=\"right\">\n");
      out.write("					<ul class=menu>\n");
      out.write("						<!-- 인증이후 -->\n");
      out.write("							<li class=username><span></span></li>\n");
      out.write("							<li><a href=\"\">나의정보</a></li>\n");
      out.write("							<li><a href=\"\">로그아웃</a></li>\n");
      out.write("										\n");
      out.write("							<li><a href=\"\">로그인</a></li>\n");
      out.write("							<li><a href=\"\">회원가입</a></li>\n");
      out.write("						\n");
      out.write("						<!-- 공통 -->\n");
      out.write("						<li><a href=\"javascript:void(0)\">고객센터</a></li>\n");
      out.write("						<li><a href=\"javascript:void(0)\">전체메뉴</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("</div>");
      out.write("\n");
      out.write("			<!-- nav -->\n");
      out.write("			");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("			<nav class=layout-150>\n");
      out.write("				<!-- <div class=\"left\"></div> -->\n");
      out.write("				<div class=\"right\">\n");
      out.write("					<ul class=menu>\n");
      out.write("						<li>\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">홈</a>\n");
      out.write("\n");
      out.write("						</li>\n");
      out.write("						\n");
      out.write("						<li>\n");
      out.write("							<a href=\"\">도서관소개</a>\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"\">연혁</a></li>\n");
      out.write("								<li><a href=\"\">오시는길</a></li>\n");
      out.write("								<li><a href=\"\">기타등등</a></li>\n");
      out.write("							</ul>\n");
      out.write("						</li>\n");
      out.write("						\n");
      out.write("						<li>\n");
      out.write("							<a href=\"\">공지사항</a>\n");
      out.write("							<!-- \n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"\">공지사항게시판</a></li>\n");
      out.write("								<li><a href=\"\">SUBMENU2</a></li>\n");
      out.write("								<li><a href=\"\">SUBMENU3</a></li>\n");
      out.write("							</ul>\n");
      out.write("							 -->\n");
      out.write("						</li>\n");
      out.write("						<li>\n");
      out.write("							<a href=\"\">도서서비스</a>\n");
      out.write("							<ul>\n");
      out.write("								\n");
      out.write("								<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/list\">도서조회[ALL]</a></li>\n");
      out.write("								<li><a href=\"javascript:void(0)\">도서대여신청[회원]</a></li>\n");
      out.write("								<li><a href=\"\">대여신청확인[사서]</a></li>\n");
      out.write("								<li><a href=\"\">예약신청확인[사서]</a></li>\n");
      out.write("								<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/add\">도서등록[사서]</a></li>\n");
      out.write("								<li><a href=\"\">도서수정[사서]</a></li>\n");
      out.write("								<li><a href=\"\">도서삭제[사서]</a></li>\n");
      out.write(" 								\n");
      out.write("							</ul>\n");
      out.write("						</li>\n");
      out.write("						<li>\n");
      out.write("							<a href=\"\">자유게시판</a>\n");
      out.write("							<!-- \n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"\">SUBMENU1</a></li>\n");
      out.write("								<li><a href=\"\">SUBMENU2</a></li>\n");
      out.write("								<li><a href=\"\">SUBMENU3</a></li>\n");
      out.write("							</ul>\n");
      out.write("							 -->\n");
      out.write("						</li>\n");
      out.write("						<li>\n");
      out.write("							<a href=\"\">행사일정</a>\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"\">연간행사</a></li>\n");
      out.write("								<li><a href=\"\">이번달행사</a></li>\n");
      out.write("								<li><a href=\"\">...</a></li>\n");
      out.write("							</ul>\n");
      out.write("						</li>\n");
      out.write("						<li>\n");
      out.write("							<a href=\"\">자주하는질문</a>\n");
      out.write("							<ul>\n");
      out.write("								<li><a href=\"\">QnA</a></li>\n");
      out.write("								<li><a href=\"\">FAQ</a></li>\n");
      out.write("							</ul>\n");
      out.write("						</li>\n");
      out.write("																														\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</nav>	");
      out.write("\n");
      out.write("\n");
      out.write("		</header>\n");
      out.write("       <main>\n");
      out.write("            <section class=\"banner-section\">\n");
      out.write("                    <!-- Slider main container -->\n");
      out.write("                    <div class=\"swiper\">\n");
      out.write("                        <!-- Additional required wrapper -->\n");
      out.write("                        <div class=\"swiper-wrapper\">\n");
      out.write("                            <!-- Slides -->\n");
      out.write("                            <div class=\"swiper-slide\">  <a href=\"javascript:void(0)\"><img src=\"\" alt=\"\"> </a>   </div>\n");
      out.write("                            <div class=\"swiper-slide\">  <a href=\"javascript:void(0)\"><img src=\"\" alt=\"\"> </a>   </div>\n");
      out.write("                            <div class=\"swiper-slide\">  <a href=\"javascript:void(0)\"><img src=\"\" alt=\"\"> </a>   </div>\n");
      out.write("                            <div class=\"swiper-slide\">  <a href=\"javascript:void(0)\"><img src=\"\" alt=\"\"> </a>   </div>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        <!-- If we need pagination -->\n");
      out.write("                        <div class=\"swiper-pagination\"> </div>\n");
      out.write("                    \n");
      out.write("                        <!-- If we need navigation buttons -->\n");
      out.write("                        <div class=\"swiper-button-prev\">\n");
      out.write("                            <span class=\"material-symbols-outlined\">arrow_left</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"swiper-button-next\">\n");
      out.write("                            <span class=\"material-symbols-outlined\">arrow_right</span>\n");
      out.write("                        </div>\n");
      out.write("                    \n");
      out.write("                        <!-- If we need scrollbar -->\n");
      out.write("                        <div class=\"swiper-scrollbar\"></div>\n");
      out.write("                    </div>\n");
      out.write("            </section>\n");
      out.write("            \n");
      out.write("            <!-- 다중슬라이더 구현 -->\n");
      out.write("            <section class=\"multi-slider\">\n");
      out.write("                    <!-- Slider main container -->\n");
      out.write("                    <div class=\"swiper\">\n");
      out.write("                        <!-- Additional required wrapper -->\n");
      out.write("                        <div class=\"swiper-wrapper\">\n");
      out.write("                            <!-- Slides -->\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"swiper-slide\">\n");
      out.write("                                <a href=\"javascript:void(0)\">\n");
      out.write("                                    <img src=\"\" alt=\"\">\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write(" \n");
      out.write("                        </div>\n");
      out.write("                        <!-- If we need pagination -->\n");
      out.write("                        <div class=\"swiper-pagination\"></div>\n");
      out.write("                    \n");
      out.write("                        <!-- If we need navigation buttons -->\n");
      out.write("                        <div class=\"swiper-button-prev\">\n");
      out.write("                            <span class=\"material-symbols-outlined\">arrow_left</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"swiper-button-next\">\n");
      out.write("                            <span class=\"material-symbols-outlined\">arrow_right</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <section></section>\n");
      out.write("        </main>\n");
      out.write("        \n");
      out.write("        	<footer>\n");
      out.write("        		<!-- footer  -->\n");
      out.write("				");
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("        	</footer>\n");
      out.write("        	\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("\n");
      out.write("</body>	\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
